### PR TITLE
Multi site RFC

### PR DESCRIPTION
**Pull request by sureyeaah**
[**Rendered**](https://github.com/sureyeaah/neuron/blob/multi-site/guide/rfc-multi-site.md#generating-multiple-sites)

Addresses #222

### CODE REVIEW

**Comment by srid** [comment]
BTW, table rendering is broken: https://github.com/sureyeaah/neuron/blob/multi-site/guide/rfc-multi-site.md#generating-multiple-sites

GitHub [does support it](https://docs.github.com/en/github/writing-on-github/organizing-information-with-tables), so I wonder what could be wrong. Perhaps something to do with newlines?

**Comment by srid** [comment]
A third way of solving this is to consider #50 but in local context. Suppose there are two *local* zettelkastens -- private & public -- we could make it possible for one zettelkasten to (cross) link to another (but *not* vice versa). So "public" zettelkasten would be independent; but the "private" zettelkasten can cross link to the "public" zettels.  Coming up with a spec to make this work doesn't seem exactly easy though.

**Comment by srid** [comment]
Thinking more about _cross-linking_ ... instead of having sub-zettelkastens, we now think in terms of _composing_ (otherwise independent) zettelkastens.

So, if you have a zettelkasten called "public" -- and it exists as a sub-directory (or git submodule) as ./public/neuron.dhall -- then you can have another zettelkasten's neuron.dhall "point" to it as `{ "public" = ./public }`. This another zettelkasten can now link to the public zettelkasten using an ID prefix. For example, to link to ./public/foo.md - you would write `<public:foo>`. Its graph would include the zettels from "public" but with this ID prefix. The generated HTML would go in a sub-directory, i.e., `public/foo.html`.

This also solves the problem of public/index.html being in conflict with the master zettelkasten's zettel of same ID.

And it solves the constraint of "public" zettelkasten being allowed only to link to itself (unless it is configured to have cross-links)

**Comment by sureyeaah** [comment]
How does this affect querying? If I query by a tag, is it supposed to query cross-links as well or is there a special syntax for choosing an ID prefix?

**Comment by srid** [comment]
Since both the zettelkastens will be part of the same graph, if you say query by tag - it will include zettels from both of them.

To be more precise, it is not exactly cross-linking - rather, more of "embedding" another zettelkasten into your graph ... but with IDs namespaced. Here, you would be embedding your blog zettelkasten onto your private zettelkasten.

**Comment by srid** [comment]
Closing in favour of #355

**Pull request closed without merging**
