### PR TITLE
Add missing modules in neuron.cabal

### PR DESCRIPTION
**Pull request by Lysxia**

### CODE REVIEW

**Comment by Lysxia** [comment]
Oh wait no, there is no HeadHTML

**Comment by srid** [comment]
HeadHtml should really be in src/app, not src/lib - because library cannot and should not depend on `shake` (it must compile on ghcjs).

**Comment by Lysxia** [comment]
Okay, should be fixed

**Comment by Lysxia** [comment]
Oh lol I failed my fix. Thanks!

**Pull request merged**
