### PR TITLE
feat: Added § in whitelist

### LINKED ISSUE #595: Files with `§` in title not recognized
I'm currently using the `§` character to add structure to my ZK (`§§`, `§1`, etc). 
I think this character is not recognized by neuron

Steps to reproduce

1. Create a file test.md
2. Create a second file `§2\ test.md`
3. Link the second file in the first file 
4. Only the first file will be recognized

### PR DESCRIPTION
**Pull request by danymat**
Closes #595

### CODE REVIEW

**Comment by srid** [comment]
@danymat Could also increase the version (a.b.1.d -> a.b.2.e), and add to CHANGELOG?

**Comment by danymat** [comment]
Fixed

**Comment by danymat** [comment]
@srid Is the docker automatically updated? I still don't see the whitelist changes in my GitHub actions (it still doesn't allow `§`), even that I saw last docker modification 15m ago

**Comment by srid** [comment]
It's done in CI https://github.com/srid/neuron/runs/2318867734#step:7:85

**Comment by srid** [comment]
And it works for me. Make sure that `neuron --version` is 1.9.26.0 or later.

**Comment by danymat** [comment]
Weird, in same neuron version, both from docker and local:

Updated neuron
```
Plugins enabled: links, tags, neuronignore, uptree
Loading directory tree (333 .md files) ...
Building graph (332 notes) ...
Building route data ...
Rendering routes (333 slugs) ...
```

On docker
```
  Plugins enabled: links, tags, neuronignore, uptree
   Loading directory tree (333 .md files) ...
   Building graph (117 notes) ...
   Building route data ...
   Rendering routes (118 slugs) ...
``

**Comment by danymat** [comment]
@srid Oh I know, As I'm on Mac, I use special characters like é, è, ... 
In docker the files that contain these character are not recognized by neuron

**Pull request merged**
