### PR TITLE
Document systemd+home-manager usage

### PR DESCRIPTION
**Pull request by Nadrieril**

### CODE REVIEW

**Comment by srid** [comment]
Nice. Can you put this on its own zettel?

(In future, I plan to create a 'Deployment' zettel, and then your zettel could be put under that along with CI/CD setup zettels)

**Comment by Nadrieril** [comment]
If I do, from where should I link to it?

**Comment by srid** [comment]
For now, link to it from "Declarative Install".

>

**Comment by Nadrieril** [comment]
Done

**Pull request merged**
